### ISSUE TITLE
$GW2_ALT_BASE/conf/GFXSettings.GW2-64.exe.xml file naming + a couple of other issues

### ISSUE THREAD

**Issue by nick3white** [Iiridayn/gw2-linux-multibox-launcher#1]
I'm going through the script and I had few issues I figured I'd share.  First was this one - which was especially frustrating because the solution was literally staring me in the face the entire time. 

line 53:
```
if [ ! -d "$GW2_ALT_BASE/conf" ] || [ ! -f "$GW2_ALT_BASE/conf/GFXSettings.GW2-64.exe.xml" ]; then
```

it took me an embarrassingly long time to realize that my GFX file was actually named 

```
GFXSettings.Gw2-64.exe.xml
```
I didn't rename my file - I just copied it straight over to the .config directory, so that name is the default for my installation (lutris built on a windows install) - so I'm not sure if that's a typo on your end or just a legit difference in the potential filenames - but it might be worth mentioning if there are different filename variants.

The next issue is related (I hope!) to first launches.  I have 5 accounts, and I started with 
```
./gw2-alt.sh -c 01 
```
let it start up, then I would do the next - 
```
./gw2-alt.sh -c 01 02
```
and so on until 05.  However, every time I would launch a new one for the first time, it would hang on the GW2 launcher screen - just before iyou get to the login, there's a 'downloading' and then a 'initializing'  - it hung on 'initializing'.  The only time I had the patience to let it sit for a while, it eventually provided the following error:
```
 XGetWindowProperty failed!
```
The final issue is that the login screen isn't remembering the usernames and passwords - I'm hoping there's an easy fix for that - it's not the end of the world, but it's a littke tedious

I'm running arch btw, i3wm; AMD graphics card, not sure if that matters.

**Comment by Iiridayn** [comment]
Nice, also running i3wm in arch w/an AMD GPU :).

The filename difference is legitimate - windows is not case sensitive, and I had a similar problem with the `GW2-64.exe` file a couple years ago (was or now is `Gw2-64.exe` or something); not sure how to best fix that offhand, but we should definitely address it if possible. Looks like my work computer uses `Gw2-64.exe` and `GFXSettings.Gw2-64.exe.xml`, while my home computer uses `GW2-64.exe` and `GFXSettings.GW2-64.exe.xml`, so I should have a test case when I have time to fix it.

Can run `gw2-alt.sh -c 01 02 03 04 05` all at once; the script launches each one at a time in order. If you've already done `gw2-alt.sh -c 01` there's no reason to do `gw2-alt.sh -c 01 02` - can just do `gw2-alt.sh -c 02` if you'd like to mount and run each individually.

When first configuring accounts, did you follow the steps at https://github.com/Iiridayn/gw2-linux-multibox-launcher#initial-setup? In particular, you have to launch each with `-o` to be able to change saved usernames and passwords or settings, and can only launch one at a time to do that.

**Comment by Iiridayn** [comment]
Okay, didn't take that long. Fixed the GFXSettings file thing to check the executable name first.

**Comment by nick3white** [comment]
Nice - your fix was definitely more elegant than the one I wrote.

> When first configuring accounts, did you follow the steps at https://github.com/Iiridayn/gw2-linux-multibox-launcher#initial-setup? In particular, you have to launch each with -o to be able to change saved usernames and passwords or settings, and can only launch one at a time to do that.

I did, and then I didn't ;) I read the list steps and then didn't read the paragraph text after, which was kinda important. 

I'm still having trouble with the startup though - last night i didn't have time to dig in, but I keep getting the error where it just hangs indefinitely while trying to start the first account.  I'll try to spend some time with it tonight get more info.

**Comment by Iiridayn** [comment]
It's possibly waiting for the PID file, which might be getting dropped in the wrong directory. I'll double check that I removed all the hard-coded paths.

**Comment by Iiridayn** [comment]
Try uncommenting lines 147 and 150; if you're not getting a PID, that'd be the problem; line 161 would then be in an infinite loop.

Flow is: enter from top of script, `$OPT_RUN` is true so execute the `if` body from 263. This runs `setsid`, effectively forking the script, then calls `waitrun`, which loops once a second at line 161 waiting for the forked instance to create the pid file.

The `setsid` forked instance starts w/the test on line 209, which calls `runwithpid`; this calls `run` in the background which runs your `$WINE` variable (defaults to just `wine`) with the game executable path...

I've updated the game executable path to ensure it uses the same case as the actual file, though that's not been an issue for me yet.

The `setsid` forked instance runs your `$WINE` variable with the correct game executable path, then loops once a second waiting for `ps` to show the process running in the same session created by `setsid`. If you echo the session on line 147, you can run the first part of line 149 manually to see if the game is failing to launch - `ps -s <session id>`.

I suspect `$WINE` might be wrong; maybe double check your `~/.config/gw2alts/config.sh` file? That file should have any environment variables needed from your working CLI launch script when just running your main alone. If you don't have one of those working, poke me on Discord for interactive support.

**Comment by nick3white** [comment]
Ok, I was finally able to dig into this last night.  The first thing I did was to start from scratch, to follow the instructions again, since there was obviously at least one bit I had missed.  After deleting everything and starting fresh, I was able to start up all accounts with the simple `./gw2-alts 1 2 3...` line.  

The issue I was having with it failing to get a PID - that was weird, because it would work if I started with -c or -o or -co - but it seems to be fine now.  It didn't happen for all accounts, so I think it was related to which accounts I initiated correctly and which ones I didn't.

One last question (unless this acts up again!!) do you know where should I put the .dll for Arc DPS?  I only really want it on my main account - but it didn't load when I put it in the "default" location (`~/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2`) or the version from this script (`~/config/gw2alts/main/drive_c/Program Files/Guild Wars 2`).

**Comment by Iiridayn** [comment]
That is odd - I keep mine in `~/Games/guild-wars-2/drive_c/Program Files/Guild Wars 2/d3d11.dll`. Ah - do you have the line `export WINEDLLOVERRIDES="d3d11=n,b;winemenubuilder="` (not sure if the menubuilder thing is required) in your setup or otherwise have the wineprefix configured for `d3d11.dll` overrides? I believe that's a standard step in setting up ArcDPS in `wine`, which might not have been replicated in the alt setup.
